language: java

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
addons:
  sonarcloud:
    organization: "temabensa"
    token:
      secure: "$SONAR_TOKEN"
  script:
    - sonar-scanner
deploy:
  provider: heroku
  api_key:
      secure: "HEROKU_API_KEY"
  app: tema-bensa