language: java

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

deploy:
  provider: heroku
  api_key:
      secure: "2c97166d-4beb-4bf2-917b-d58bdc2c41de"