language: java
sudo: false

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

addons:
  sonarcloud:
    organization: "temabensa"
    token:
      secure: "$SONAR_TOKEN"
before_script:
  - chmod +x gradlew
script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
after_succes:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: heroku
  api_key:
      secure: "2c97166d-4beb-4bf2-917b-d58bdc2c41de"
  app: screenerd