language: java

jdk:
  - oraclejdk8

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

install:
  gradle assemble

script:
  ./gradlew --no-daemon check

  deploy:
    provider: heroku
    api_key:
      secure: "$HEROKU_API_KEY"
    app: tema-bensa

after_failure:
  "$TRAVIS_TEST_RESULT"