language: java

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

install:
  gradle assemble

  deploy:
    provider: heroku
    api_key:
      secure: "$HEROKU_API_KEY"
    app: tema-bensa